---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-vol-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
